### ISSUE TITLE
Remove usage of IsoCountry and IsoCurrency enums from public API

### ISSUE THREAD

**Issue by marcwrobel** [marcwrobel/jbanking#10]
Even if they can be useful IsoCountry and IsoCurrency enums must not be used in the public API :
- They are here for convenience and are not absolutely required in the scope of this library.
- The enum implementation is not the right solution because those standards are not "static" and may evolve over time. We do not want a new jbanking release each time one of those standard is updated.
- The java platform already supports those standards for quite some times. See the [Currency](http://docs.oracle.com/javase/7/docs/api/java/util/Currency.html) and the [Locale](http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html) classes for more informations.
- There are some alternatives in case enums are really needed. See [nv-i18n](https://github.com/TakahikoKawasaki/nv-i18n) for instance.

**Comment by marcwrobel** [comment]
Those enums will still be available, at least for internal and testing purposes, but will not be a first class citizen of the jbanking API anymore.

**Comment by davehoch** [comment]
Is there any plan to have [Bic.isValid()](https://github.com/marcwrobel/jbanking/blob/d17fa71e6ee0e0a62722ab60d9e95e937b6f165f/src/main/java/fr/marcwrobel/jbanking/bic/Bic.java#L97) use Locale for country codes instead of IsoCountry?  That would push the country maintenance on to Java instead jbanking.

**Comment by marcwrobel** [comment]
There is no plan yet. Feel free to contribute if you have some time.

**Comment by marcwrobel** [comment]
As of today ISO Country code list retrieved using `Locale.getISOCountries()` is nearly identical to the country codes in `IsoCountry`, except for :
* [AN](https://en.wikipedia.org/wiki/ISO_3166-2:AN) : on OpenJDK 8.0.242 this code is still present, even if it was removed from ISO Country list in 2010 (no present on OpenJDK 11.0.6).
* [XK](https://en.wikipedia.org/wiki/Postal_codes_in_Kosovo), the temporary code for Kosovo, is not present in both OpenJDK 8.0.242 and OpenJDK 11.0.6.

**Comment by marcwrobel** [comment]
After some thought on the subject I decided to put this issue aside.

It would be best to do not have a new jbanking release each time one of the ISO-3166 or ISO-4217 standard is updated but  :
* We cannot push the maintenance burden for those standards onto java because, even if it is nearly complete in JDK 8 and 11, support changed from version to version and there is still missing or deprecated entries.
* We cannot push the maintenance burden for those standards onto nv-i18n because it is not banking-oriented and contains deprecated entries (ISO-4217).
* It is very easy to use.
* Some features may take advantage of those enums (#31 for instance).
* Those enums are very useful when developing a banking application (in my own experience).

Having say that, it may be useful to have an integration with `java.util.Locale` or `java.util.Currency`.
