### ISSUE TITLE
IBAN patterns

### ISSUE THREAD

**Issue by PaulWoods4422** [marcwrobel/jbanking#15]
From the test data I have it seems the Costa Rica pattern is wrong - should be "3!n15!n" (not 14!n ).
You are also missing Kosovo:
Iban Structure:
 KOSOVO(IsoCountry.KOSOVO,"4!n10!n2!n")

ISoCountry:
 KOSOVO("XK"),

**Comment by marcwrobel** [comment]
Hi @PaulWoods4422, those issues has been fixed in #16 by an update of the BBAN structures to match IBAN Registry Release 78 (some BBAN structures were outdated).
