### ISSUE TITLE
Add IBAN generation

### ISSUE THREAD

**Issue by marcwrobel** [marcwrobel/jbanking#153]
Add the ability to generate valid IBANs for test purposes.

**Comment by aSemy** [comment]
Hi, can I make a couple of requests for this feature?

* Allow setting the `Random` as a method argument, so I can pass in a seeded `Random`. This helps with deterministic testing (useful for property based testing), so I can generate the same IBANs repeatedly.
* Provide this as a separate test dependency, e.g. `fr.marcwrobel:jbanking-test-utils`. I'd really prefer to keep code for test purposes out of the main library dependencies. 

Any random generation would be useful though - these enhancements can be added later. Thanks for the consideration!

**Comment by marcwrobel** [comment]
Hi @aSemy, thanks for your inputs.

For the deterministic part sure, that's a really good idea.

For the separate test dependency I agree with you. But I am not sure it is worth the trouble : adding a new library is a lot of work compared to embed this feature directly in jbanking.

**Comment by aSemy** [comment]
Agreed. It can always be refactored later!
