### ISSUE TITLE
Update BBAN Structure

### ISSUE THREAD

**Issue by mocken** [marcwrobel/jbanking#17]
According to https://www.swift.com/standards/data-standards/iban the BBAN Structure for Turkey changed to:

    TURKEY(IsoCountry.TURKEY, "5!n1!n16!c"),

and a new structure was added for Vatican City:

VATICAN_CITY_STATE(IsoCountry.VATICAN_CITY_STATE, "3!n15!n")

**Comment by marcwrobel** [comment]
Hi @mocken, BBAN structure update will be done in #30.
