### ISSUE TITLE
Could you contribute BIC validator to org.apache.commons.validator?

### ISSUE THREAD

**Issue by stokito** [marcwrobel/jbanking#18]
I need to validate both IBAN and BIC just by simple format check and decided to use Apache Commons Validator instead of jbanking because don't wan't to have Guava as transitive dependency.
Commons Validator has the [IBANValidator](https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/IBANValidator.html) but it haven't anything to validate BIC.
Could you send PR to Commons Validator with your BIC validator?

**Comment by marcwrobel** [comment]
Hi @stokito,

As you can see it in the pom, the Guava dependency is a test dependency. It is not needed for normal use of the jbanking library. So if you still want it you can use jbanking in your project without having to depend on Guava.

I will not contribute a BICValidator to the Apache Commons Validator library. But feel free to do it by looking at how the [Bic class](https://github.com/marcwrobel/jbanking/blob/master/src/main/java/fr/marcwrobel/jbanking/bic/Bic.java) works.
