### ISSUE TITLE
Valid IBAN Value returns Invalid

### ISSUE THREAD

**Issue by tddiaz** [marcwrobel/jbanking#19]
Given this IBAN Value "JO69WXCV8898216666923864119419", The Iban.isValid() returns false.

Confirmed the mentioned iban was valid using IBANValidator of apache commons validator and from from https://www.ibancalculator.com/iban_validieren.html

**Comment by marcwrobel** [comment]
Hi @tddiaz, Jordan IBANs are not supported by jbanking 1.0 (Jordan IBAN was not part of the IBAN registry until February 2014 and the release 1.0 of jbanking was released in 2013).

This issue has been fixed in #14 and a new version of jbanking will be released soon.
