### ISSUE TITLE
ISO 9362:2014 support ?

### ISSUE THREAD

**Issue by marcwrobel** [marcwrobel/jbanking#66]
Is there anything to do to support ISO 9362:2014 BIC ?

**Comment by marcwrobel** [comment]
Acccording to https://www.swift.com/swift-resource/14256/download?language=en the BIC structure does not change. So nothing to do.

**Comment by boubech** [comment]
Hello, 
The BIC format is prefixed by the institution code. 
This code is an alphanumeric of length 4 but the method checks that the code is only alphabetic.
 https://github.com/marcwrobel/jbanking/blob/4c881384d81e166ccac0ab631b51385eb2ce2431/src/main/java/fr/marcwrobel/jbanking/bic/Bic.java#L184-L203
