### ISSUE TITLE
Is this library useful for converting bank accounts between national and IBAN format?

### ISSUE THREAD

**Issue by breakline87** [marcwrobel/jbanking#67]
I checked the use case but havent found this. I want to convert between national and IBAN formats but havent found anything working anywhere. Before writing it myself I'm considering libraries which might have this functionality.

**Comment by marcwrobel** [comment]
Hi @breakline87,

jbanking knows how to convert a national account number to an IBAN. In jbanking national account number are called BBAN, e.g. [Basic Bank Account Number](https://en.wikipedia.org/wiki/International_Bank_Account_Number#Structure).

As an example you can have a look a this piece of code with the Hungarian bank account number you provided in https://github.com/arturmkrtchyan/iban4j/issues/83 :
```
  @Test
  void test() {
    Iban iban1 = new Iban("HU74116000060000000034953226");
    System.out.println(iban1.getBban()); // 116000060000000034953226

    Iban iban2 = new Iban(IsoCountry.HU, "116000060000000034953226");
    System.out.println(iban2.getBban()); // 116000060000000034953226
    System.out.println(iban2.toString()); // HU74116000060000000034953226
    System.out.println(iban2.toPrintableString()); // HU74 1160 0006 0000 0000 3495 3226

   Iban iban3 = new Iban("HU74116000060000000000000000"); // fr.marcwrobel.jbanking.iban.IbanFormatException: 'HU74116000060000000000000000' check digits are incorrect

    Iban iban4 = new Iban(IsoCountry.HU, "116"); // fr.marcwrobel.jbanking.iban.IbanFormatException: '116' BBAN structure is not valid against BBAN structure used in HU
  }
```

You can see in this example :
- `iban2` : given an IBAN jbanking can extract the corresponding BBAN
- `iban2` : given an ISO country code and a BBAN, jbanking can compute the corresponding IBAN
- `iban3` : given an IBAN jbanking validate the check digits
- `iban4` : given a BBAN (or an IBAN) jbanking validate the BBAN format (see also https://github.com/marcwrobel/jbanking/blob/master/src/main/java/fr/marcwrobel/jbanking/iban/BbanStructure.java)

Does this example answer your questions?

**Comment by breakline87** [comment]
Thank you!
